# Inspect CTest's resolved properties, including Catch's generated discovery
# files. Misparsed lists can silently discard timeouts and skip return codes.
if(DEFINED TEST_METADATA_FILE)
    file(READ "${TEST_METADATA_FILE}" metadata)
else()
    execute_process(COMMAND "${TEST_CTEST_COMMAND}" --test-dir "${TEST_BUILD_DIR}"
        -C "${TEST_CONFIGURATION}" --show-only=json-v1
        -R "^(Allocation|Native|Capture completion|Native allocation|Stress|Native stress|Face network):"
        RESULT_VARIABLE result OUTPUT_VARIABLE metadata ERROR_VARIABLE error
        TIMEOUT 20)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Could not inspect CTest metadata: ${result}\n${error}")
    endif()
endif()

function(check_properties test name expected_labels expected_timeout)
    string(JSON count LENGTH "${test}" properties)
    math(EXPR last "${count} - 1")
    set(labels)
    set(timeout)
    set(skip)
    foreach(index RANGE ${last})
        string(JSON property GET "${test}" properties ${index})
        string(JSON key GET "${property}" name)
        if(key STREQUAL "LABELS")
            string(JSON label_count LENGTH "${property}" value)
            math(EXPR last_label "${label_count} - 1")
            foreach(label_index RANGE ${last_label})
                string(JSON label GET "${property}" value ${label_index})
                list(APPEND labels "${label}")
            endforeach()
        elseif(key STREQUAL "TIMEOUT")
            string(JSON timeout GET "${property}" value)
        elseif(key STREQUAL "SKIP_RETURN_CODE")
            string(JSON skip GET "${property}" value)
        endif()
    endforeach()
    list(SORT labels)
    if(NOT labels STREQUAL expected_labels OR NOT skip STREQUAL "4")
        message(FATAL_ERROR "${name}: labels '${labels}' (expected '${expected_labels}'), skip '${skip}' (expected 4)")
    endif()
    if(NOT expected_timeout STREQUAL "" AND NOT timeout EQUAL expected_timeout)
        message(FATAL_ERROR "${name}: timeout '${timeout}' (expected ${expected_timeout})")
    endif()
endfunction()

string(JSON count LENGTH "${metadata}" tests)
if(count EQUAL 0)
    message(FATAL_ERROR "No labeled tests were discovered")
endif()
math(EXPR last "${count} - 1")
set(checked 0)
foreach(index RANGE ${last})
    string(JSON test GET "${metadata}" tests ${index})
    string(JSON name GET "${test}" name)
    if(name MATCHES "^(Capture completion|Native allocation):")
        check_properties("${test}" "${name}" "allocation;native" 30)
    elseif(name MATCHES "^Allocation:")
        check_properties("${test}" "${name}" allocation 30)
    elseif(name MATCHES "^Native:")
        check_properties("${test}" "${name}" native "")
    elseif(name MATCHES "^(Stress|Native stress):")
        check_properties("${test}" "${name}" stress 300)
    elseif(name MATCHES "^Face network:")
        check_properties("${test}" "${name}" face-network 60)
    else()
        continue()
    endif()
    math(EXPR checked "${checked} + 1")
endforeach()
if(checked EQUAL 0)
    message(FATAL_ERROR "No recognized test metadata was checked")
endif()
message(STATUS "Verified labels, timeouts and skip codes for ${checked} tests")
