if(NOT DEFINED MODEL_INPUT OR NOT DEFINED MODEL_OUTPUT)
    message(FATAL_ERROR "MODEL_INPUT and MODEL_OUTPUT are required")
endif()
file(SHA256 "${MODEL_INPUT}" actual_hash)
if(NOT actual_hash STREQUAL "8f2383e4dd3cfbb4553ea8718107fc0423210dc964f9f4280604804ed2552fa4")
    message(FATAL_ERROR "The face detection model does not match its pinned SHA-256")
endif()
file(READ "${MODEL_INPUT}" model HEX)
string(LENGTH "${model}" length)
get_filename_component(directory "${MODEL_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${directory}")
set(temporary "${MODEL_OUTPUT}.tmp")
file(WRITE "${temporary}" "#include \"platform/windows/face_model_data.h\"\n\nnamespace sidescopes {\nnamespace {\nconstexpr unsigned char Model[] = {\n")
set(offset 0)
while(offset LESS length)
    math(EXPR remaining "${length} - ${offset}")
    if(remaining GREATER 128)
        set(remaining 128)
    endif()
    string(SUBSTRING "${model}" ${offset} ${remaining} row)
    string(REGEX REPLACE "(..)" "0x\\1," row "${row}")
    file(APPEND "${temporary}" "${row}\n")
    math(EXPR offset "${offset} + ${remaining}")
endwhile()
file(APPEND "${temporary}" "};\n}  // namespace\n\nstd::span<const unsigned char> faceModelBytes()\n{\n    return Model;\n}\n\n}  // namespace sidescopes\n")
file(RENAME "${temporary}" "${MODEL_OUTPUT}")
