# Replace one compiled DNN source without changing the fetched source tree.
function(sidescopes_replace_dnn_source original generated)
    if(NOT TARGET opencv_dnn)
        message(FATAL_ERROR "Configure OpenCV before replacing a DNN source")
    endif()
    get_target_property(sources opencv_dnn SOURCES)
    set(replacement "")
    set(matches 0)
    foreach(source IN LISTS sources)
        if(source STREQUAL original)
            list(APPEND replacement "${generated}")
            math(EXPR matches "${matches} + 1")
        else()
            list(APPEND replacement "${source}")
        endif()
    endforeach()
    if(NOT matches EQUAL 1)
        message(FATAL_ERROR "Expected exactly one upstream OpenCV source: ${original}")
    endif()
    set_property(TARGET opencv_dnn PROPERTY SOURCES "${replacement}")
    get_filename_component(include_dir "${original}" DIRECTORY)
    target_include_directories(opencv_dnn PRIVATE "${include_dir}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}")
endfunction()
